spring:
  cloud:
    client:
      hostname: library-service
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/biglibon
    username: biglibon
    password: biglibon
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Improves SQL readability
        use_sql_comments: true # Adds comments in logs

eureka:
  instance:
    prefer-ip-address: true # overwrite on docker-compose as false
    hostname: library-service # overwrite on docker-compose as library-service
    instance-id: ${spring.application.name}:${hostname}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

server:
  port: 0 # Random port assignment, overwrite on docker-compose as 8887, because can not open random port

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # Shows executed SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # Shows parameter bindings
    org.springframework.web: info
    web: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

spring.cloud.service-registry.auto-registration.enabled: true
