# based on the profile first this yaml is read then the others override this
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # defaults to "local" if not set
  application:
    name: library-service
  cloud:
    client:
      hostname: library-service
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Improves SQL readability
#        use_sql_comments: true # Adds comments in logs
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    hostname: library-service
    instance-id: ${spring.application.name}:${random.uuid}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0

logging:
  level:
    #    root: INFO
    #    org.hibernate.SQL: DEBUG  # Shows executed SQL queries
    #    org.hibernate.type.descriptor.sql: TRACE  # Shows parameter bindings
    #    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    #    org.springframework.web: info
    #    web: debug
    org.springframework.kafka: INFO
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.internals: WARN

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # localhost:8888/library-service/actuator/health

spring.cloud.service-registry.auto-registration.enabled: true
