spring:
  application:
    name: library-service
  jpa:
    #    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibarnate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Improves SQL readability
        use_sql_comments: true # Adds comments in logs
  datasource:
    url: jdbc:postgresql://localhost:5432/biglibon
    username: biglibon
    password: biglibon
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

server:
  port: 0 # Random port assignment

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # Shows executed SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # Shows parameter bindings
    org.springframework.web: info
    web: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"