spring:
  application:
    name: shared-library
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: false
    properties:
      enable.auto.commit: false
      security.protocol: PLAINTEXT
    producer:
      acks: all
    consumer:
      group-id: biglibon-consumer-group
      auto-offset-reset: earliest

kafka:
  kraft:
    mode: true
    process-roles: "controller,broker"
    node-id: 1
    controller-quorum-voters: "1@localhost:9093"
    listeners: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
    listener-security-protocol-map: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
    inter-broker-listener-name: "PLAINTEXT"
    controller-listener-names: "CONTROLLER"
    advertised-listeners: "PLAINTEXT://localhost:9092"
    log-dirs: "/var/lib/kafka/data"
    auto-create-topics-enable: false
    offsets-topic-replication-factor: 1
    log-retention-hours: 168
    group-initial-rebalance-delay-ms: 0
    cluster-id: "Biglibon-Mk3OEYBSD34fcwNTJENDM2Qk"