# application-{profile}.yaml using spring.profiles.active:{profile} for us application-docker.yaml
spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo-db}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:biglibon}
      username: ${SPRING_DATA_MONGODB_USERNAME:biglibon}
      password: ${SPRING_DATA_MONGODB_PASSWORD:biglibon}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-4:9092,kafka-5:9092,kafka-6:9092,kafka-7:9092}
    properties:
      security.protocol: PLAINTEXT
  elasticsearch:
    uris: https://es01:9200
    username: elastic
    password: ${ELASTIC_PASSWORD:biglibon}
    ssl:
      enabled: true
      certificate-authorities: file:///catalog-service/elasticsearch/certs/ca/ca.crt

eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
