services:
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.1.0
    restart: unless-stopped
    container_name: kafka-ui
    read_only: true
    networks:
      - biglibon-network
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-4:9092,kafka-5:9092,kafka-6:9092,kafka-7:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_METRICS_TYPE: JMX
      DYNAMIC_CONFIG_ENABLED: true
    ports:
      - 127.0.0.1:${KAFKA_UI_PORT}:8080/tcp
    depends_on:
      kafka-4:
        condition: service_healthy
      kafka-5:
        condition: service_healthy
      kafka-6:
        condition: service_healthy
      kafka-7:
        condition: service_healthy

  kafka-1:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-1
    networks:
      - biglibon-network
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_JMX_PORT: 9997
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh list-endpoints --bootstrap-controller localhost:9093
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s

  kafka-2:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-2
    networks:
      - biglibon-network
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_JMX_PORT: 9997
    volumes:
      - kafka-2-data:/var/lib/kafka/data
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh list-endpoints --bootstrap-controller localhost:9093
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      - kafka-1

  kafka-3:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-3
    networks:
      - biglibon-network
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_JMX_PORT: 9997
    volumes:
      - kafka-3-data:/var/lib/kafka/data
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh list-endpoints --bootstrap-controller localhost:9093
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      - kafka-2

  kafka-4:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-4
    networks:
      - biglibon-network
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4 # important set as broker numbers we have 4 default 3 ensures each partition is replicated across all brokers. Max redundancy
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-4:9092,EXTERNAL://${KAFKA_4_IP}:${KAFKA_4_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_USERNAME}" \
        password="${KAFKA_PASSWORD}" \
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
      KAFKA_JMX_PORT: 9997
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-4-data:/var/lib/kafka/data
    ports:
      - ${KAFKA_4_PORT}:9094/tcp
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  kafka-5:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-5
    networks:
      - biglibon-network
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4 # important set as broker numbers we have 4 default 3 ensures each partition is replicated across all brokers. Max redundancy
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-5:9092,EXTERNAL://${KAFKA_5_IP}:${KAFKA_5_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_USERNAME}" \
        password="${KAFKA_PASSWORD}" \
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
      KAFKA_JMX_PORT: 9997
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-5-data:/var/lib/kafka/data
    ports:
      - ${KAFKA_5_PORT}:9094/tcp
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  kafka-6:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-6
    networks:
      - biglibon-network
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4 # important set as broker numbers we have 4 default 3 ensures each partition is replicated across all brokers. Max redundancy
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-6:9092,EXTERNAL://${KAFKA_6_IP}:${KAFKA_6_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_USERNAME}" \
        password="${KAFKA_PASSWORD}" \
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
      KAFKA_JMX_PORT: 9997
    volumes:
      - kafka-6-data:/var/lib/kafka/data
    ports:
      - ${KAFKA_6_PORT}:9094/tcp
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  kafka-7:
    image: docker.io/apache/kafka:4.0.0
    restart: unless-stopped
    container_name: kafka-7
    networks:
      - biglibon-network
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4 # important set as broker numbers we have 4 default 3 ensures each partition is replicated across all brokers. Max redundancy
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 7
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-7:9092,EXTERNAL://${KAFKA_7_IP}:${KAFKA_7_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_USERNAME}" \
        password="${KAFKA_PASSWORD}" \
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
      KAFKA_JMX_PORT: 9997
    volumes:
      - kafka-7-data:/var/lib/kafka/data
    ports:
      - ${KAFKA_7_PORT}:9094/tcp
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 1s
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

####### Volumes #######
volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
  kafka-4-data:
  kafka-5-data:
  kafka-6-data:
  kafka-7-data:

####### Networks #######
networks:
  biglibon-network: