services:
  mongo-ui:
    image: mongo-express:1.0.2-18
    container_name: mongo-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    networks:
      - biglibon-network
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:8.0.10
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - biglibon-network
    volumes:
      - mongo-db-data:/data/db

  postgres-db:
    image: postgres:17.5
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - biglibon-network

  postgres-ui:
    image: dpage/pgadmin4:9.4.0
    container_name: postgres-ui
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - biglibon-network
    volumes:
      - postgres-ui-data:/var/lib/pgadmin
    depends_on:
      - postgres-db

####### Volumes #######
volumes:
  mongo-db-data:
  postgres-ui-data:
  postgres-db-data:

####### Networks #######
networks:
  biglibon-network:
