spring:
  application:
    name: api-gateway
  cloud:
    client:
      hostname: api-gateway
    gateway:
      server:
        webflux:
          routes:
            # book-service
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/v1/books/**
            # book-service-actuator
            - id: book-service-actuator
              uri: lb://book-service
              predicates:
                - Path=/book-service/actuator/**
              filters:
                - StripPrefix=1 # delete first segment book-service for the actual service
            # library-service
            - id: library-service
              uri: lb://library-service
              predicates:
                - Path=/v1/libraries/**
            # library-service-actuator
            - id: library-service-actuator
              uri: lb://library-service
              predicates:
                - Path=/library-service/actuator/**
              filters:
                - StripPrefix=1 # delete first segment library-service for the actual service
            # catalog-service
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/v1/catalogs/**
            # catalog-service-actuator
            - id: catalog-service-actuator
              uri: lb://catalog-service
              predicates:
                - Path=/catalog-service/actuator/**
              filters:
                - StripPrefix=1 # delete first segment catalog-service for the actual service
          discovery:
            locator:
              enabled: true

server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10  # Heartbeat check time
    prefer-ip-address: true # overwrite on docker-compose as false
    hostname: ${spring.cloud.client.hostname} # overwrite on docker-compose as api-gateway
    instance-id: ${spring.application.name}:${random.uuid}:${eureka.instance.hostname}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

management:
  endpoints:
    web:
      exposure:
        include: "*" # localhost:8888/actuator/health

logging:
  level:
    com.netflix.discovery: DEBUG

spring.cloud.service-registry.auto-registration.enabled: true
