spring:
  application:
    name: api-gateway
  cloud:
    client:
      hostname: api-gateway
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/v1/books/**
            - id: library-service
              uri: lb://library-service
              predicates:
                - Path=/v1/libraries/**
          discovery:
            locator:
              enabled: true

server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10   # Heartbeat check time
    prefer-ip-address: true # overwrite on docker-compose as false
    hostname: api-gateway # overwrite on docker-compose as api-gateway
    instance-id: ${spring.application.name}:${hostname}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

management:
  endpoints:
    web:
      exposure:
        include: "*" # adds all actuator endpoints (like health (shows that app is live?))

logging:
  level:
    com.netflix.discovery: DEBUG

spring.cloud.service-registry.auto-registration.enabled: true
