# based on the profile first this yaml is read then the others override this
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # defaults to "local" if not set
  application:
    name: book-service
  cloud:
    client:
      hostname: book-service
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true # neye yarıyor bakılacak
  jpa:
    show-sql: true
  kafka:
    consumer:
      group-id: book-service-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    hostname: book-service
    leaseRenewalIntervalInSeconds: 10   # Heartbeat check time
    instance-id: ${spring.application.name}:${random.uuid}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.internals: WARN

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

spring.cloud.service-registry.auto-registration.enabled: true