# application-{profile}.yaml using spring.profiles.active:{profile} for us application-local.yaml
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: biglibon
      username: biglibon
      password: biglibon
  kafka:
    bootstrap-servers: localhost:9094,localhost:9095,localhost:9096,localhost:9097
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: |
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="biglibon"
        password="biglibon";

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka