spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # defaults to "local" if not set
  application:
    name: book-service
  cloud:
    client:
      hostname: book-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: biglibon
      username: biglibon
      password: biglibon
      authentication-database: admin
      auto-index-creation: true
  jpa:
    show-sql: true
  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094,localhost:9095,localhost:9096,localhost:9097}
    consumer:
      group-id: book-service-consumer-group

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10   # Heartbeat check time
    prefer-ip-address: true # overwrite on docker-compose as false
    hostname: ${spring.cloud.client.hostname} # overwrite on docker-compose as book-service
    instance-id: ${spring.application.name}:${random.uuid}:${eureka.instance.hostname}:${server.port}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

server:
  port: 0 # Random port assignment, overwrite on docker-compose as 8887, because can not open random port

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients.consumer.internals: WARN

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

spring.cloud.service-registry.auto-registration.enabled: true